language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libgfortran3:i386

install:
    - pip install -r requirements.txt
script:
    - py.test